---
title: "Bachelor"
author: "Andreas Matre"
date: "2/11/2020"
output: 
  pdf_document:
    toc: true
    number_sections: true
        #html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(survey)
library(ggplot2)
library(ggfortify)
library(cowplot)
library(dplyr)
```




```{r, include = FALSE}
anthsrs <- SDaA::anthsrs
anthuneq <- SDaA::anthuneq
anthuneq$weights <- 1/anthuneq$prob
anthuneq$height = anthuneq$height*2.54
anthsrs$height = anthsrs$height*2.54

anthsrs$fpc <- 3000
anthuneq$fpc <- 3000
```

```{r, echo = FALSE, warning = FALSE}
base <- ggplot() + xlim(10, 13) + ylim(145, 191) +
  theme(axis.title = element_text(size = 20), axis.text = element_text(size = 15)) +
  ylab("Height (cm)") + xlab("Finger length (cm)")
  
srsdots <- base + geom_point(data = anthsrs, aes(finger, height))

uneqdots <- base + geom_point(data = anthuneq, aes(finger, height))
```


```{r}
anthuneq.svy <- svydesign(ids = ~0, weights = ~weights, fpc = ~fpc, data = anthuneq)
anthsrs.svy <- svydesign(ids = ~0, fpc = ~fpc, data = anthsrs)

normalmoduneq <- lm(height ~ finger, data = anthuneq)
survmoduneq <- svyglm(height ~ finger, design = anthuneq.svy)

normalmodsrs <- lm(height ~finger, data = anthsrs)
survmodsrs <- svyglm(height ~ finger, design = anthsrs.svy)

normalcoefuneq <- summary(normalmoduneq)$coefficients
survcoefuneq <- summary(survmoduneq)$coefficients

normalcoefsrs <- summary(normalmodsrs)$coefficients
survcoefsrs <- summary(survmodsrs)$coefficients
```

```{r}
## Bootstrap
#B = 10000
#
#coefs <- sapply(1:B, function(x) {
#  indeces <- sample(1:nrow(anthuneq), size = nrow(anthuneq), replace = TRUE)
#  s <- anthuneq[indeces,]
#  s.svy <- svydesign(ids = ~0, weights = ~weights, data = s)
#  mod <- svyglm(height ~ finger, design = s.svy)
#  return(summary(mod)$coefficients[,1])
#})
#
#intercept.var <- var(coefs[1,])
#finger.var <- var(coefs[2,])
#intercept.finger.cov <- cov(coefs[1,], coefs[2,])

```

```{r}
x.vals = seq(from = 9.5, to = 13.5, by = 0.1)
#predict.int.normalmod <- as.data.frame(predict(normalmod, newdata = data.frame(finger = x.vals), interval = "pred"))
#predict.int.normalmod$x.vals <- x.vals

normal.cov.uneq <- vcov(normalmoduneq)
predict.normalmoduneq <- predict(normalmoduneq, newdata = data.frame(finger = x.vals))
predict.int.normalmoduneq <- data.frame(fit = predict.normalmoduneq)
predict.int.normalmoduneq$x.vals <- x.vals
predict.int.normalmoduneq$se <- sqrt(summary(normalmoduneq)$sigma^2 + normal.cov.uneq[1, 1] + predict.int.normalmoduneq$x.vals^2 * normal.cov.uneq[2, 2] + 2*predict.int.normalmoduneq$x.vals * normal.cov.uneq[1, 2])
predict.int.normalmoduneq$lwr <- predict.int.normalmoduneq$fit - predict.int.normalmoduneq$se * qt(0.975, df = nrow(anthuneq))
predict.int.normalmoduneq$upr <- predict.int.normalmoduneq$fit + predict.int.normalmoduneq$se * qt(0.975, df = nrow(anthuneq))

surv.cov.uneq <- vcov(survmoduneq)

predict.survmoduneq <- as.data.frame(predict(survmoduneq, newdata = data.frame(finger = x.vals), se=TRUE))
predict.int.survmoduneq <- data.frame(fit = predict.survmoduneq$link)
predict.int.survmoduneq$x.vals <- x.vals
predict.int.survmoduneq$se <- sqrt(var(survmoduneq$residuals) + surv.cov.uneq[1, 1] + predict.int.survmoduneq$x.vals^2 * surv.cov.uneq[2, 2] + 2*predict.int.survmoduneq$x.vals * surv.cov.uneq[1, 2])
predict.int.survmoduneq$lower <- predict.int.survmoduneq$fit - predict.int.survmoduneq$se * qt(0.975, df = nrow(anthuneq))
predict.int.survmoduneq$upper <- predict.int.survmoduneq$fit + predict.int.survmoduneq$se * qt(0.975, df = nrow(anthuneq))

# Tester innebygd SE
predict.survmoduneq <- as.data.frame(predict(survmoduneq, newdata = data.frame(finger = x.vals), se=TRUE))
predict.survmoduneq$x.vals <- x.vals
predict.survmoduneq$fit <- predict.survmoduneq$link
predict.survmoduneq$lower <- predict.survmoduneq$fit - predict.survmoduneq$SE * qt(0.975, df = nrow(anthuneq))
predict.survmoduneq$upper <- predict.survmoduneq$fit + predict.survmoduneq$SE * qt(0.975, df = nrow(anthuneq))

head(as.data.frame(predict(survmoduneq, newdata = data.frame(finger = x.vals), vcov = TRUE, se.fit = TRUE)))

normal.cov.srs <- vcov(normalmodsrs)
predict.normalmodsrs <- predict(normalmodsrs, newdata = data.frame(finger = x.vals))
predict.int.normalmodsrs <- data.frame(fit = predict.normalmodsrs)
predict.int.normalmodsrs$x.vals <- x.vals
predict.int.normalmodsrs$se <- sqrt(summary(normalmodsrs)$sigma^2 + normal.cov.srs[1, 1] + predict.int.normalmodsrs$x.vals^2 * normal.cov.srs[2, 2] + 2*predict.int.normalmodsrs$x.vals * normal.cov.srs[1, 2])
predict.int.normalmodsrs$lwr <- predict.int.normalmodsrs$fit - predict.int.normalmodsrs$se * qt(0.975, df = nrow(anthsrs))
predict.int.normalmodsrs$upr <- predict.int.normalmodsrs$fit + predict.int.normalmodsrs$se * qt(0.975, df = nrow(anthsrs))

surv.cov.srs <- vcov(survmodsrs)

predict.survmodsrs <- as.data.frame(predict(survmodsrs, newdata = data.frame(finger = x.vals), se=TRUE))
predict.int.survmodsrs <- data.frame(fit = predict.survmodsrs$link)
predict.int.survmodsrs$x.vals <- x.vals
predict.int.survmodsrs$se <- sqrt(var(survmodsrs$residuals) + surv.cov.srs[1, 1] + predict.int.survmodsrs$x.vals^2 * surv.cov.srs[2, 2] + 2*predict.int.survmodsrs$x.vals * surv.cov.srs[1, 2])
predict.int.survmodsrs$lower <- predict.int.survmodsrs$fit - predict.int.survmodsrs$se * qt(0.975, df = nrow(anthsrs))
predict.int.survmodsrs$upper <- predict.int.survmodsrs$fit + predict.int.survmodsrs$se * qt(0.975, df = nrow(anthsrs))
```

```{r}
percent.in.pred.val(SDaA::anthrop$finger, SDaA::anthrop$height*2.54, predict.int.survmoduneq$x.vals, predict.int.survmoduneq$lower, predict.int.survmoduneq$upper)
```


```{r}
size.uneq <- rep(0.8, length(nrow(anthuneq)))
size.srs <- rep(0.8, length(nrow(anthuneq)))


srs.plot <- base +
  geom_ribbon(aes(x = x.vals, ymin = lower, ymax = upper), data = predict.int.survmodsrs, fill = "blue", alpha = 0.5) +
  geom_ribbon(aes(x = x.vals, ymin = lwr, ymax = upr), data = predict.int.normalmodsrs, fill = "red", alpha = 0.5) +
  geom_point(data = anthsrs, aes(finger, height), size = size.srs) +
  geom_abline(slope = survcoefsrs[2], intercept = survcoefsrs[1], color = "blue", lwd = 1) +
  geom_line(data = predict.int.survmodsrs, aes(x = x.vals, y = lower), color = "blue", linetype = "dashed") +
  geom_line(data = predict.int.survmodsrs, aes(x = x.vals, y = upper), color = "blue", linetype = "dashed") +
  geom_abline(slope = normalcoefsrs[2], intercept = normalcoefsrs[1], color = "red", lwd = 1) +
  geom_line(data = predict.int.normalmodsrs, aes(x = x.vals, y = lwr), color = "red", linetype = "dashed") +
  geom_line(data = predict.int.normalmodsrs, aes(x = x.vals, y = upr), color = "red", linetype = "dashed")

uneq.plot <- base +
  geom_ribbon(aes(x = x.vals, ymin = lower, ymax = upper), data = predict.int.survmoduneq, fill = "blue", alpha = 0.5) +
  geom_ribbon(aes(x = x.vals, ymin = lwr, ymax = upr), data = predict.int.normalmoduneq, fill = "red", alpha = 0.5) +
  geom_point(data = anthuneq, aes(finger, height), size = size.uneq) +
  geom_abline(slope = survcoefuneq[2], intercept = survcoefuneq[1], color = "blue", lwd = 1) +
  geom_line(data = predict.int.survmoduneq, aes(x = x.vals, y = lower), color = "blue", linetype = "dashed") +
  geom_line(data = predict.int.survmoduneq, aes(x = x.vals, y = upper), color = "blue", linetype = "dashed") +
  geom_abline(slope = normalcoefuneq[2], intercept = normalcoefuneq[1], color = "red", lwd = 1) +
  geom_line(data = predict.int.normalmoduneq, aes(x = x.vals, y = lwr), color = "red", linetype = "dashed") +
  geom_line(data = predict.int.normalmoduneq, aes(x = x.vals, y = upr), color = "red", linetype = "dashed")

# Sammenligner prediksjonsintervall for innebygd SE og manuelt utregnet. Rød er innebydt, blå er manuell
base +
  geom_ribbon(aes(x = x.vals, ymin = lower, ymax = upper), data = predict.int.survmoduneq, fill = "blue", alpha = 0.5) +
  geom_ribbon(aes(x = x.vals, ymin = lower, ymax = upper), data = predict.survmoduneq, fill = "red", alpha = 0.5) +
  geom_point(data = anthsrs, aes(finger, height), size = size.uneq) +
  geom_abline(slope = survcoefuneq[2], intercept = survcoefuneq[1], color = "blue", lwd = 1) +
  geom_line(data = predict.int.survmoduneq, aes(x = x.vals, y = lower), color = "blue", linetype = "dashed") +
  geom_line(data = predict.int.survmoduneq, aes(x = x.vals, y = upper), color = "blue", linetype = "dashed") +
  #geom_abline(slope = normalcoefuneq[2], intercept = normalcoefuneq[1], color = "red", lwd = 1) +
  geom_line(data = predict.survmoduneq, aes(x = x.vals, y = lower), color = "red", linetype = "dashed") +
  geom_line(data = predict.survmoduneq, aes(x = x.vals, y = upper), color = "red", linetype = "dashed")

plot_grid(srsdots, uneqdots, srs.plot, uneq.plot, ncol = 2)
```

```{r}
ggsave("images/ex1.pdf", height = 18, units = "cm")
setwd("images/")
pdf("ex1Pred.pdf")
print(plot_grid(srs.plot, uneq.plot, ncol = 2))
dev.off()
```



# Stratification

```{r}
data(api)
```


```{r}
apistrat %>% filter(stype == "H") %>% nrow
apistrat %>% filter(stype == "M") %>% nrow
apistrat %>% filter(stype == "E") %>% nrow

apipop %>% filter(stype == "H") %>% nrow
apipop %>% filter(stype == "M") %>% nrow
apipop %>% filter(stype == "E") %>% nrow
```

```{r}
svy.srs <- svydesign(id = ~1, weights = ~pw, data = apisrs, fpc = ~fpc)
svy.strat <- svydesign(id=~1,strata=~stype, weights=~pw, data=apistrat, fpc=~fpc)

svymean(~api00, svy.srs)
svymean(~api00, svy.strat)
```

```{r}
apipop %>% filter(hsg > 30) %>% transmute(mean = mean(api00))
foo <- apipop %>% filter(hsg > 30) %>% select(api00) %>% mean
mean((apipop %>% filter(hsg < 40) %>% filter(hsg > 30))$api00)
mean((apipop %>% filter(hsg > 70))$api00)
mean((apipop %>% filter(col.grad < 20))$api00)
mean((apipop %>% filter(col.grad > 20) %>% filter(col.grad < 40))$api00)
mean((apipop %>% filter(col.grad > 40))$api00)

length((apipop %>% filter(col.grad < 20))$api00)
length((apipop %>% filter(col.grad > 20) %>% filter(col.grad < 40))$api00)
length((apipop %>% filter(col.grad > 40))$api00)
```

```{r}
api.less.than.20 <- apipop %>% filter(col.grad < 20)
api.less.than.20$pw <- nrow(api.less.than.20)/100
api.less.than.20$fpc <- nrow(api.less.than.20)
api.less.than.20$stype <- 1

api.between.20.40 <- apipop %>% filter(col.grad > 20) %>% filter(col.grad < 40)
api.between.20.40$pw <- nrow(api.between.20.40)/100
api.between.20.40$fpc <- nrow(api.between.20.40)
api.between.20.40$stype <- 2

api.more.than.40 <- apipop %>% filter(col.grad > 40)
api.more.than.40$pw <- nrow(api.more.than.40)/100
api.more.than.40$fpc <- nrow(api.more.than.40)
api.more.than.40$stype = 3

apistratcol <- api.less.than.20[sample(1:nrow(api.less.than.20), 100, replace = F),]
apistratcol <- rbind(apistratcol, api.between.20.40[sample(1:nrow(api.between.20.40), 100, replace = F),])
apistratcol <- rbind(apistratcol, api.more.than.40[sample(1:nrow(api.more.than.40), 100, replace = F),])

apisrs300 <- apipop[sample(1:nrow(apipop), 300, replace = F),]
apisrs300$pw <- nrow(apipop)/300
apisrs300$fpc <- nrow(apipop)

```


```{r}
svy.srs <- svydesign(id = ~1, weights = ~pw, data = apisrs300, fpc = ~fpc)
svy.strat <- svydesign(id=~1,strata=~stype, weights=~pw, data=apistratcol, fpc=~fpc)

svymean(~api00, svy.srs)
svymean(~api00, svy.strat)
mean(apipop$api00)
```


```{r}
plot(x = apipop$api99, y = apipop$api00)
plot(x = apipop$target, y = apipop$api00)
plot(x = apipop$meals, y = apipop$api00)
plot(x = apipop$ell, y = apipop$api00)
plot(x = apipop$mobility, y = apipop$api00)
plot(x = apipop$acs.k3, y = apipop$api00)
plot(x = apipop$acs.46, y = apipop$api00)
plot(x = apipop$not.hsg, y = apipop$api00)
plot(x = apipop$hsg, y = apipop$api00)
plot(x = apipop$some.col, y = apipop$api00)
plot(x = apipop$col.grad, y = apipop$api00)
plot(x = apipop$grad.sch, y = apipop$api00)
plot(x = apipop$avg.ed, y = apipop$api00)
plot(x = apipop$full, y = apipop$api00)
plot(x = apipop$emer, y = apipop$api00)
```

```{r}
api.pop.strat.not.hsg <- apipop %>% mutate(strat = case_when(not.hsg < 20 ~ 1, TRUE ~ 2))
api.strat.not.hsg <- api.pop.strat.not.hsg[stratsample(api.pop.strat.not.hsg$strat, c("1" = 100, "2" = 100)),]
api.strat.not.hsg$pw <- case_when(api.strat.not.hsg$strat == 1 ~ sum(api.pop.strat.not.hsg$strat == 1) / 100, api.strat.not.hsg$strat == 2 ~ sum(api.pop.strat.not.hsg$strat == 2) / 100)
api.strat.not.hsg$fpc <- case_when(api.strat.not.hsg$strat == 1 ~ sum(api.pop.strat.not.hsg$strat == 1), api.strat.not.hsg$strat == 2 ~ sum(api.pop.strat.not.hsg$strat == 2))

(api.strat.not.hsg %>% filter(strat == 2))$pw

svy.srs <- svydesign(id = ~1, weights = ~pw, data = apisrs, fpc = ~fpc)
svy.strat <- svydesign(id=~1,strata=~strat, weights=~pw, data=api.strat.not.hsg, fpc=~fpc)

summary(svyglm(api00 ~ not.hsg, design = svy.srs))
summary(svyglm(api00 ~ not.hsg, design = svy.strat))

# Stratifiser på api99
```

```{r}
api.pop.strat.api99 <- apipop %>% mutate(strat = case_when(api99 < 500 ~ 1, api99 >= 500 & api99 < 750 ~ 2, api99 >= 750 ~ 3))
api.strat.api99 <- api.pop.strat.api99[stratsample(api.pop.strat.api99$strat, c("1" = 100, "2" = 100, "3" = 100)),]
api.strat.api99$pw <- case_when(api.strat.api99$strat == 1 ~ sum(api.pop.strat.api99$strat == 1) / 100, api.strat.api99$strat == 2 ~ sum(api.pop.strat.api99$strat == 2) / 100, api.strat.api99$strat == 3 ~ sum(api.pop.strat.api99$strat == 3) / 100)
api.strat.api99$fpc <- case_when(api.strat.api99$strat == 1 ~ sum(api.pop.strat.api99$strat == 1), api.strat.api99$strat == 2 ~ sum(api.pop.strat.api99$strat == 2), api.strat.api99$strat == 3 ~ sum(api.pop.strat.api99$strat == 3))

apisrs300 <- apipop[sample(1:nrow(apipop), 300, replace = F),]
apisrs300$pw <- nrow(apipop)/300
apisrs300$fpc <- nrow(apipop)

(api.strat.api99 %>% filter(strat == 2))$pw

svy.srs <- svydesign(id = ~1, weights = ~pw, data = apisrs300, fpc = ~fpc)
svy.strat <- svydesign(id=~1,strata=~strat, weights=~pw, data=api.strat.api99, fpc=~fpc)

summary(svyglm(api00 ~ not.hsg, design = svy.srs))
summary(svyglm(api00 ~ not.hsg, design = svy.strat))

summary(lm(api00 ~ not.hsg, data = apipop))

ggplot(data = api.strat.api99, aes(x = not.hsg, y = api00)) + geom_point()
ggplot(data = apisrs300, aes(x = not.hsg, y = api00)) + geom_point()
```

```{r}
mod1 <- lm(api00 ~ as.factor(stype) * col.grad, data = apipop)
mod2 <- lm(api00 ~ as.factor(stype) + col.grad, data = apipop)

anova(mod1, mod2)

counts <- sapply(table(apipop$cnum), function(i) min(5, i))
api.strat.cnum <- apipop[stratsample(apipop$cnum, counts),]
api.strat.cnum <- api.strat.cnum %>% mutate(fpc = table(apipop$cnum)[cnum])
svy.api.strat.cnum <- svydesign(id=~1,strata=~cnum, data=api.strat.cnum, fpc=~fpc)

api.strat.cnum.svymod <- svyglm(api00 ~ acs.k3, design = svy.api.strat.cnum)
summary(api.strat.cnum.svymod)

api.strat.stype.505050 <- apipop[stratsample(apipop$stype, counts = c("E" = 50, "M" = 50, "H" = 50)),]
api.strat.stype.505050 <- api.strat.stype.505050 %>% mutate(fpc = table(apipop$stype)[stype])
api.strat.stype.505050 <- api.strat.stype.505050 %>% mutate(pw = table(apipop$stype)[stype] / table(api.strat.stype.505050$stype)[stype])

svy.api.strat.stype.505050 <- svydesign(id=~1,strata=~stype, weights=~pw, data=api.strat.stype.505050, fpc=~fpc)
api.strat.svymod <- svyglm(api00 ~ avg.ed, design = svy.api.strat.stype.505050)
api.strat.normmod <- lm(api00 ~ avg.ed, data = apistrat)
summary(api.strat.svymod)
summary(api.strat.normmod)
```

```{r}
modE <- svyglm(api00 ~ avg.ed, design = subset(svy.api.strat.stype.505050, stype == "E"))
modM <- svyglm(api00 ~ avg.ed, design = subset(svy.api.strat.stype.505050, stype == "M"))
modH <- svyglm(api00 ~ avg.ed, design = subset(svy.api.strat.stype.505050, stype == "H"))

coef(api.strat.svymod)
coef(modE)
coef(modM)
coef(modH)

confint(api.strat.svymod, parm = "avg.ed")
confint(modE, parm = "avg.ed")
confint(modM, parm = "avg.ed")
confint(modH, parm = "avg.ed")

coef(lm(api00 ~ avg.ed, data = (apipop %>% filter(stype == "E"))))
coef(lm(api00 ~ avg.ed, data = (apipop %>% filter(stype == "M"))))
coef(lm(api00 ~ avg.ed, data = (apipop %>% filter(stype == "H"))))

ggplot(data = apistrat, aes(avg.ed, api00, colour = stype)) + geom_point() + geom_abline(intercept = coef(api.strat.svymod)[1], slope = coef(api.strat.svymod)[2])
```

## Eksempel unequal probabilities

```{r}
set.seed(123)
A <- rnorm(1000, mean = 0, sd = 1)
B <- rnorm(1000, mean = 10, sd = 1)

tot <- sum(A) + sum(B)

A.sample.100 <- A[sample(1:1000, 100, replace = F)]
B.sample.100 <- B[sample(1:1000, 100, replace = F)]

tot.est.100.100 <- sum(A.sample.100 * 1000/100) + sum(B.sample.100 * 1000/100)

A.sample.50 <- A[sample(1:1000, 50, replace = F)]

tot.est.wrong.50.100 <- sum(c(A.sample.50, B.sample.100)) * 2000/150
tot.est.correct.50.100 <- 1000/50 * sum(A.sample.50) + 1000/100 * sum(B.sample.100)
```



# Clustering

```{r}
# Lage egen one-stage cluster på dnum
# ER NOE FEIL, ALT FOR LITE PREDIKSJONSINTERVALL

n <- 100
dnums <- unique(apipop$dnum)[sample(1:length(unique(apipop$dnum)), n, replace = F)]

dnumclus <- apipop %>% filter(dnum %in% dnums)
dnumclus$pw <- length(unique(apipop$dnum)) / n
dnumclus$fpc <- length(unique(apipop$dnum))

svy.dnum <- svydesign(id = ~dnum, weights = ~pw, fpc = ~fpc, data = dnumclus)
dnum.clus.svymod <- svyglm(api00 ~ avg.ed, design = svy.dnum)
summary(dnum.clus.svymod)

base + geom_point(data = dnumclus, aes(avg.ed, api00), color = "red") + geom_point(data = apiclus1, aes(avg.ed, api00), color = "blue")
```


```{r}
apiclus1$pw = 757/15
svy.clus <- svydesign(id = ~dnum, weights = ~pw, fpc = ~fpc, data = apiclus1)

api.clus.svymod <- svyglm(api00 ~ avg.ed, design = svy.clus)
summary(api.clus.svymod)

#api.clus.normmod <- lm(api00 ~ avg.ed, data = apiclus1)
#summary(api.clus.normmod)

api.srs.clus <- dnumclus
api.srs.clus$pw <- length(unique(apipop$dnum)) / length(unique(dnumclus$dnum))
api.srs.clus$fpc <- length(unique(apipop$dnum))

svy.api.srs.clus <- svydesign(id = ~1, weights = ~pw, fpc = ~fpc, data = api.srs.clus)

api.clus.srs.svymod <- svyglm(api00 ~ avg.ed, design = svy.api.srs.clus)
summary(api.clus.srs.svymod)

api.srs.183 <- apipop[sample(1:nrow(apipop), 183, replace = F),]
api.srs.183$pw <- nrow(apipop) / 183
api.srs.183$fpc <- nrow(apipop)

svy.api.srs.183 <- svydesign(id = ~1, weights = ~pw, fpc = ~fpc, data = api.srs.183)

api.srs.183.svymod <- svyglm(api00 ~ avg.ed, design = svy.api.srs.183)
```

```{r}
x.vals = seq(from = 1, to = 5, by = 0.01)

clus.srs.svy.cov <- vcov(api.clus.srs.svymod)
predict.api.clus.srs.svymod <- as.data.frame(predict(api.clus.srs.svymod, newdata = data.frame(avg.ed = x.vals), se=TRUE))
predict.int.api.clus.srs.svymod <- data.frame(fit = predict.api.clus.srs.svymod$link)
predict.int.api.clus.srs.svymod$x.vals <- x.vals
predict.int.api.clus.srs.svymod$se <- sqrt(var(api.clus.srs.svymod$residuals) + clus.srs.svy.cov[1, 1] + predict.int.api.clus.srs.svymod$x.vals^2 * clus.srs.svy.cov[2, 2] + 2*predict.int.api.clus.srs.svymod$x.vals * clus.srs.svy.cov[1, 2])
predict.int.api.clus.srs.svymod$lower <- predict.int.api.clus.srs.svymod$fit - predict.int.api.clus.srs.svymod$se * qt(0.975, df = nrow(apipop))
predict.int.api.clus.srs.svymod$upper <- predict.int.api.clus.srs.svymod$fit + predict.int.api.clus.srs.svymod$se * qt(0.975, df = nrow(apipop))

clus.svy.cov <- vcov(api.clus.svymod)
predict.api.clus.svymod <- as.data.frame(predict(api.clus.svymod, newdata = data.frame(avg.ed = x.vals), se=TRUE))
predict.int.api.clus.svymod <- data.frame(fit = predict.api.clus.svymod$link)
predict.int.api.clus.svymod$x.vals <- x.vals
predict.int.api.clus.svymod$se <- sqrt(var(api.clus.svymod$residuals) + clus.svy.cov[1, 1] + predict.int.api.clus.svymod$x.vals^2 * clus.svy.cov[2, 2] + 2*predict.int.api.clus.svymod$x.vals * clus.svy.cov[1, 2])
predict.int.api.clus.svymod$lower <- predict.int.api.clus.svymod$fit - predict.int.api.clus.svymod$se * qt(0.975, df = nrow(apiclus1))
predict.int.api.clus.svymod$upper <- predict.int.api.clus.svymod$fit + predict.int.api.clus.svymod$se * qt(0.975, df = nrow(apiclus1))

srs.183.svy.cov <- vcov(api.srs.183.svymod)
predict.api.srs.183.svymod <- as.data.frame(predict(api.srs.183.svymod, newdata = data.frame(avg.ed = x.vals), se=TRUE))
predict.int.api.srs.183.svymod <- data.frame(fit = predict.api.srs.183.svymod$link)
predict.int.api.srs.183.svymod$x.vals <- x.vals
predict.int.api.srs.183.svymod$se <- sqrt(var(api.srs.183.svymod$residuals) + srs.183.svy.cov[1, 1] + predict.int.api.srs.183.svymod$x.vals^2 * srs.183.svy.cov[2, 2] + 2*predict.int.api.srs.183.svymod$x.vals * srs.183.svy.cov[1, 2])
predict.int.api.srs.183.svymod$lower <- predict.int.api.srs.183.svymod$fit - predict.int.api.srs.183.svymod$se * qt(0.975, df = nrow(apipop))
predict.int.api.srs.183.svymod$upper <- predict.int.api.srs.183.svymod$fit + predict.int.api.srs.183.svymod$se * qt(0.975, df = nrow(apipop))

dnum.clus.svy.cov <- vcov(dnum.clus.svymod)
predict.dnum.clus.svymod <- as.data.frame(predict(dnum.clus.svymod, newdata = data.frame(avg.ed = x.vals), se=TRUE))
predict.int.dnum.clus.svymod <- data.frame(fit = predict.dnum.clus.svymod$link)
predict.int.dnum.clus.svymod$x.vals <- x.vals
predict.int.dnum.clus.svymod$se <- sqrt(var(dnum.clus.svymod$residuals) + dnum.clus.svy.cov[1, 1] + predict.int.dnum.clus.svymod$x.vals^2 * dnum.clus.svy.cov[2, 2] + 2*predict.int.dnum.clus.svymod$x.vals * dnum.clus.svy.cov[1, 2])
predict.int.dnum.clus.svymod$lower <- predict.int.dnum.clus.svymod$fit - predict.int.dnum.clus.svymod$se * qt(0.975, df = nrow(dnumclus))
predict.int.dnum.clus.svymod$upper <- predict.int.dnum.clus.svymod$fit + predict.int.dnum.clus.svymod$se * qt(0.975, df = nrow(dnumclus))
```

```{r}
# Find percent inside prediction interval
percent.in.pred.val <- function(pred, resp, x.vals, lower, upper) {
  notNA <- complete.cases(pred, resp)
  pred <- pred[notNA]
  resp <- resp[notNA]
  inside <- sapply(1:length(pred), function(i) {
    if (min(abs(pred[i] - x.vals)) < 10^-5) {
      index <- which.min(abs(x.vals - pred[i]))
      return(resp[i] >= lower[index] & resp[i] <= upper[index])
    }
    index <- which.min(abs(x.vals - pred[i]))
    meanLower <- 0.5*(lower[index] + lower[index + 1])
    meanUpper <- 0.5*(upper[index] + upper[index + 1])
    return(resp[i] >= meanLower & resp[i] <= meanUpper)
  })
  
  return(sum(inside)/length(inside))
}

percent.in.pred.val(apipop$avg.ed, apipop$api00, predict.int.api.srs.183.svymod$x.vals, predict.int.api.srs.183.svymod$lower, predict.int.api.srs.183.svymod$upper)
percent.in.pred.val(apipop$avg.ed, apipop$api00, predict.int.api.clus.svymod$x.vals, predict.int.api.clus.svymod$lower, predict.int.api.clus.svymod$upper)
percent.in.pred.val(apipop$avg.ed, apipop$api00, predict.int.api.clus.srs.svymod$x.vals, predict.int.api.clus.srs.svymod$lower, predict.int.api.clus.srs.svymod$upper)
percent.in.pred.val(apipop$avg.ed, apipop$api00, predict.int.dnum.clus.svymod$x.vals, predict.int.dnum.clus.svymod$lower, predict.int.dnum.clus.svymod$upper)
```


```{r}
min(apipop$api00)
max(apipop$api00)
```


```{r}
api.clus.svymod.coef <- coef(api.clus.svymod)
api.clus.srs.svymod.coef <- coef(api.clus.srs.svymod)

base <- ggplot() + xlim(1, 5) + ylim(300, 1100) +
  theme(axis.title = element_text(size = 20), axis.text = element_text(size = 15)) +
  ylab("API") + xlab("Average education")

base +
  geom_point(data = apipop, aes(avg.ed, api00)) +
  geom_point(data = apiclus1, aes(avg.ed, api00), color = "green") +
  geom_ribbon(aes(x = x.vals, ymin = lower, ymax = upper), data = predict.int.api.clus.srs.svymod, fill = "blue", alpha = 0.5) +
  geom_ribbon(aes(x = x.vals, ymin = lower, ymax = upper), data = predict.int.api.clus.svymod, fill = "red", alpha = 0.5) +
  geom_abline(slope = api.clus.srs.svymod.coef[2], intercept = api.clus.srs.svymod.coef[1], color = "blue", lwd = 1) +
  geom_line(data = predict.int.api.clus.srs.svymod, aes(x = x.vals, y = lower), color = "blue", linetype = "dashed") +
  geom_line(data = predict.int.api.clus.srs.svymod, aes(x = x.vals, y = upper), color = "blue", linetype = "dashed") +
  geom_abline(slope = api.clus.svymod.coef[2], intercept = api.clus.svymod.coef[1], color = "red", lwd = 1) +
  geom_line(data = predict.int.api.clus.svymod, aes(x = x.vals, y = lower), color = "red", linetype = "dashed") +
  geom_line(data = predict.int.api.clus.svymod, aes(x = x.vals, y = upper), color = "red", linetype = "dashed") 
```

```{r}
ggsave("images/exClus.pdf", height = 12, units = "cm")
```

```{r}
api.clus.svymod.coef <- coef(api.clus.svymod)
api.srs.183.svymod.coef <- coef(api.srs.183.svymod)
base +
  geom_point(data = apipop, aes(avg.ed, api00)) +
  geom_ribbon(aes(x = x.vals, ymin = lower, ymax = upper), data = predict.int.api.srs.183.svymod, fill = "blue", alpha = 0.5) +
  geom_ribbon(aes(x = x.vals, ymin = lower, ymax = upper), data = predict.int.api.clus.svymod, fill = "red", alpha = 0.5) +
  geom_abline(slope = api.srs.183.svymod.coef[2], intercept = api.srs.183.svymod.coef[1], color = "blue", lwd = 1) +
  geom_line(data = predict.int.api.srs.183.svymod, aes(x = x.vals, y = lower), color = "blue", linetype = "dashed") +
  geom_line(data = predict.int.api.srs.183.svymod, aes(x = x.vals, y = upper), color = "blue", linetype = "dashed") +
  geom_abline(slope = api.clus.svymod.coef[2], intercept = api.clus.svymod.coef[1], color = "red", lwd = 1) +
  geom_line(data = predict.int.api.clus.svymod, aes(x = x.vals, y = lower), color = "red", linetype = "dashed") +
  geom_line(data = predict.int.api.clus.svymod, aes(x = x.vals, y = upper), color = "red", linetype = "dashed")
```

```{r}
api.clus.srs.svymod.coef <- coef(api.clus.srs.svymod)
dnum.clus.svymod.coef <- coef(dnum.clus.svymod)
base +
  geom_point(data = apipop, aes(avg.ed, api00)) +
  geom_ribbon(aes(x = x.vals, ymin = lower, ymax = upper), data = predict.int.dnum.clus.svymod, fill = "blue", alpha = 0.5) +
  geom_ribbon(aes(x = x.vals, ymin = lower, ymax = upper), data = predict.int.api.clus.srs.svymod, fill = "red", alpha = 0.5) +
  geom_abline(slope = dnum.clus.svymod.coef[2], intercept = dnum.clus.svymod.coef[1], color = "blue", lwd = 1) +
  geom_line(data = predict.int.dnum.clus.svymod, aes(x = x.vals, y = lower), color = "blue", linetype = "dashed") +
  geom_line(data = predict.int.dnum.clus.svymod, aes(x = x.vals, y = upper), color = "blue", linetype = "dashed") +
  geom_abline(slope = api.clus.srs.svymod.coef[2], intercept = api.clus.srs.svymod.coef[1], color = "red", lwd = 1) +
  geom_line(data = predict.int.api.clus.srs.svymod, aes(x = x.vals, y = lower), color = "red", linetype = "dashed") +
  geom_line(data = predict.int.api.clus.srs.svymod, aes(x = x.vals, y = upper), color = "red", linetype = "dashed")
```


# Complex survey

```{r}
# Frist stage: Stratifisering på county
# Second stage: Clustering på district
```

